on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update stable
      - run: rustup target add wasm32-unknown-unknown
      - uses: taiki-e/install-action@trunk
      - run: trunk build --release
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    runs-on: ubunut-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
